name: second_project
description: A new Flutter project.


publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
  flutter_rating_bar: ^4.0.1
  provider: ^6.0.3
  font_awesome_flutter: ^10.2.1
  lottie: ^1.4.2
  shared_preferences: ^2.0.15
  dio: ^4.0.6
  otp_text_field: ^1.1.3
  fluttertoast: ^8.0.9
  carousel_slider: ^4.1.1
  smooth_page_indicator: ^1.0.0+2
  shimmer: ^2.0.0
  dependencies:
  google_maps_flutter: ^2.2.1
  geolocator: ^9.0.2
  flutter_polyline_points: ^1.0.0
  geocoding: ^2.0.5
  flutter_secure_storage: ^6.0.0
  date_picker_timeline: ^1.2.3
  intl: ^0.17.0
  flutter_rounded_date_picker: ^3.0.2
  razorpay_flutter: 1.3.2
  map_launcher: ^2.4.0
  url_launcher: ^6.1.6
  


dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^2.0.0


flutter:

 
  uses-material-design: true

 
  assets:
    - Assets/
    - Assets/images/

